# Generated by Django 4.0.2 on 2022-07-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_oldstore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewStore',
        ),
        migrations.DeleteModel(
            name='OldStore',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
