# Generated by Django 4.0.2 on 2022-07-21 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_title', models.CharField(max_length=100, null=True)),
                ('second_content', models.CharField(max_length=100, null=True)),
                ('second_app_name', models.CharField(max_length=100, null=True)),
                ('fist_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': '"order"."new_order"',
            },
        ),
    ]
