# Generated by Django 4.0.2 on 2022-07-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_oldorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldorder',
            name='fist_title',
        ),
        migrations.DeleteModel(
            name='NewOrder',
        ),
        migrations.DeleteModel(
            name='OldOrder',
        ),
    ]
